n = input('Digite algo: ')
print(f'O tipo é: {n}')
print(f'Tem apenas numeros: {n.isnumeric()}')
print(f'Tem apenas letras: {n.isalpha()}')
print(f'Tem apenas alpha-numericos: {n.isalnum()}')
print(f'É decimal: {n.isdecimal()}')
print(f'É composto apenas de espaços: {n.isspace()}')
print(f'Todas as letras são minusculas: {n.islower()}')
print(f'Todas as letras são maiusculas: {n.isupper()}')
